eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservice:
  payment-service:
    endpoints:
      uri: http://localhost:8082/payment/doPayment
  order-service:
    endpoints:
      uri: http://localhost:8081/order//place-order
  common: New 33, From Config server changes
