jwt:
  secret: 926D96C90030DD58429D2751AC1BDBBC
  exipryTimeInMillis: 3600
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: info
app:
  props:
    name: ${spring.application.name}
    id: ${spring.application.id}
    port: ${server.port}
    description: ${spring.application.description}
    
endpoints:
  catalog: http://CATALOG-SERVICE/catalog
  payment: http://PAYMENT-SERVICE/payment
